pipeline:
  name: gradledemo
  identifier: gradledemo
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1690535096848
        repoName: veera-5857/gradledemo
        build: <+input>
  stages:
    - stage:
        name: gradledemo
        identifier: gradledemo
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      gradle clean
                      gradle build
